#include "ast.h"

Dynamic_Array_Impl(Declaration*, Array_Declaration_Pointer, array_declaration_pointer_)
Dynamic_Array_Impl(Statement_Node*, Array_Statement_Node, array_statement_node_)
Dynamic_Array_Impl(Item_Node, Array_Item_Node, array_item_node_)
Dynamic_Array_Impl(Expression_Node*, Array_Expression_Node, array_expression_node_)
Dynamic_Array_Impl(Declaration, Array_Declaration, array_declaration_)
Dynamic_Array_Impl(Type*, Array_Type, array_type_)
Dynamic_Array_Impl(Array_Type, Array_Array_Type, array_array_type_)
Dynamic_Array_Impl(Statement_Assign_Part, Array_Statement_Assign_Part, array_statement_assign_part_)
Dynamic_Array_Impl(File_Node, Program, program_)
Dynamic_Array_Impl(Directive_Node, Array_Directive, array_directive_)
Dynamic_Array_Impl(Macro_Variant, Array_Macro_Variant, array_macro_variant_)
Dynamic_Array_Impl(Macro_Syntax_Data*, Array_Macro_Syntax_Data, array_macro_syntax_data_)
Dynamic_Array_Impl(Macro_Syntax_Argument, Array_Macro_Syntax_Argument, array_macro_syntax_argument_)
